### ISSUE TITLE
app is uninstallable due to pydantic.errors.PydanticImportError: 

### ISSUE THREAD

**Issue by anythingmapping** [stac-utils/qgis-stac-plugin#261]
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details. For further information visit https://errors.pydantic.dev/2.7/u/import-error

**Comment by jvdkwast** [comment]
I have the same error. QGIS 3.34.15, plugin version 1.1.2. Is there any solution?

```
Couldn't load plugin 'qgis_stac' due to an error when calling its classFactory() method 

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details. For further information visit https://errors.pydantic.dev/2.10/u/import-error 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\__init__.py", line 41, in classFactory
    from .main import QgisStac
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\main.py", line 23, in 
    from .gui.qgis_stac_widget import QgisStacWidget
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\gui\qgis_stac_widget.py", line 31, in 
    from ..gui.connection_dialog import ConnectionDialog
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\gui\connection_dialog.py", line 26, in 
    from ..api.client import Client
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\api\client.py", line 9, in 
    from .base import BaseClient
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\api\base.py", line 28, in 
    from .network import ContentFetcherTask, NetworkFetcher
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\api\network.py", line 47, in 
    from ..lib import planetary_computer as pc
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jkw\AppData\Roaming\QGIS\QGIS3\profiles\pdok\python\plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jkw\AppData\Roaming\QGIS\QGIS3\profiles\pdok\python\plugins\qgis_stac\lib\planetary_computer\sas.py", line 14, in 
    from planetary_computer.settings import Settings
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jkw\AppData\Roaming\QGIS\QGIS3\profiles\pdok\python\plugins\qgis_stac\lib\planetary_computer\settings.py", line 11, in 
    class Settings(pydantic.BaseSettings):
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pydantic\__init__.py", line 412, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.10/u/import-error


Python version: 3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.15-Prizren Prizren, 386f2583 

Python Path:
C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_plugin_gpq_downloader\ext-libs\duckdb
C:\Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins\qgis_plugin_gpq_downloader\ext-libs
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python
C:/Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\Users\jkw\Documents
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\Users\jkw\AppData\Roaming\Python\Python312\site-packages
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/jkw/AppData/Roaming/QGIS/QGIS3\profiles\pdok/python
D:/Overture
C:\Users\jkw\AppData\Roaming\QGIS\QGIS3\profiles\pdok\python\plugins\qgis_stac\lib
```

**Comment by jguelat** [comment]
@jvdkwast Did you find a solution? I'm still having this problem with QGIS 3.40 and 3.44...

**Comment by gubuntu** [comment]
same issue with me 

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.2-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/f30453dede3">f30453dede3</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.13.3</td></tr><tr><td>GDAL version</td><td>3.10.2</td></tr><tr><td>PROJ version</td><td>9.5.1</td></tr><tr><td>EPSG Registry database version</td><td>v11.022 (2024-11-05)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PostgreSQL client version</td><td>17.5</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Ubuntu 25.04</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>mapswipetool_plugin</td><td>1.3</td></tr><tr><td>giswater_qgis_plugin</td><td>3.5.007</td></tr><tr><td>Mergin</td><td>2025.3.3</td></tr><tr><td>quick_map_services</td><td>0.21.3</td></tr><tr><td>vertical_photo_placer</td><td>0.3</td></tr><tr><td>qmapcompare</td><td>1.1.1</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

**Comment by Darki21** [comment]
I have the same problem. Windows 10. QGIS 3.40.11.
The 'qgis_stac' module could not be loaded due to an error when calling the ClassFactory() method.

ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic_core\__init__.py) 
Traceback (most recent call last):
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\__init__.py", line 41, in classFactory
    from .main import QgisStac
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\main.py", line 23, in 
    from .gui.qgis_stac_widget import QgisStacWidget
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\gui\qgis_stac_widget.py", line 31, in 
    from ..gui.connection_dialog import ConnectionDialog
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\gui\connection_dialog.py", line 26, in 
    from ..api.client import Client
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\api\client.py", line 9, in 
    from .base import BaseClient
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\api\base.py", line 28, in 
    from .network import ContentFetcherTask, NetworkFetcher
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\api\network.py", line 47, in 
    from ..lib import planetary_computer as pc
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kirill\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kirill\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_stac\lib\planetary_computer\sas.py", line 9, in 
    from pydantic import BaseModel, Field
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic\__init__.py", line 435, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\game2\QGIS\apps\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic\main.py", line 36, in 
    from ._internal import (
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic\_internal\_decorators.py", line 18, in 
    from ._core_utils import get_type_ref
  File "D:\game2/QGIS/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic\_internal\_core_utils.py", line 9, in 
    from pydantic_core import validate_core_schema as _validate_core_schema
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (D:\game2\QGIS\apps\Python312\Lib\site-packages\pydantic_core\__init__.py)


Версия Python: 3.12.11 (main, Jun 17 2025, 13:41:12) [MSC v.1943 64 bit (AMD64)] 
Версия: 3.40.11-Bratislava Bratislava, df059ed19c 

Расположение Python:
C:\Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
D:/game2/QGIS/apps/qgis-ltr/./python
C:/Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/game2/QGIS/apps/qgis-ltr/./python/plugins
D:\game2\QGIS\apps\grass\grass84\etc\python
C:\Users\Kirill\Documents
D:\game2\QGIS\bin\python312.zip
D:\game2\QGIS\apps\Python312\DLLs
D:\game2\QGIS\apps\Python312\Lib
D:\game2\QGIS\bin
D:\game2\QGIS\apps\Python312
D:\game2\QGIS\apps\Python312\Lib\site-packages
D:\game2\QGIS\apps\Python312\Lib\site-packages\win32
D:\game2\QGIS\apps\Python312\Lib\site-packages\win32\lib
D:\game2\QGIS\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Kirill/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Kirill\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_stac\lib
C:/Users/Kirill/Desktop/magsitr/Komp_model/PR2

**Comment by pmagdon** [comment]
I can report the same issue with pydanti_core lib here in Windows 11.  Would love to see this fixed as it is an important tool in my workflows.  

Konnte Erweiterung 'qgis_stac' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic_core\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\__init__.py", line 41, in classFactory
    from .main import QgisStac
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\main.py", line 23, in 
    from .gui.qgis_stac_widget import QgisStacWidget
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\gui\qgis_stac_widget.py", line 31, in 
    from ..gui.connection_dialog import ConnectionDialog
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\gui\connection_dialog.py", line 26, in 
    from ..api.client import Client
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\api\client.py", line 9, in 
    from .base import BaseClient
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\api\base.py", line 28, in 
    from .network import ContentFetcherTask, NetworkFetcher
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\api\network.py", line 47, in 
    from ..lib import planetary_computer as pc
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins\qgis_stac\lib\planetary_computer\__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins\qgis_stac\lib\planetary_computer\sas.py", line 9, in 
    from pydantic import BaseModel, Field
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic\__init__.py", line 435, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic\main.py", line 36, in 
    from ._internal import (
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic\_internal\_decorators.py", line 18, in 
    from ._core_utils import get_type_ref
  File "C:\PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic\_internal\_core_utils.py", line 9, in 
    from pydantic_core import validate_core_schema as _validate_core_schema
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\pydantic_core\__init__.py)


Python-Version: 3.12.11 (main, Jun 17 2025, 13:41:12) [MSC v.1943 64 bit (AMD64)] 
QGIS-Version: 3.40.8-Bratislava Bratislava, efaf8952e0 

Python-Pfad:
C:\Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins\pdaltools
C:/PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python
C:/Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python
C:/Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python/plugins
C:/PROGRA~1/QGIS34~1.8/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS34~1.8\apps\grass\grass84\etc\python
C:\WINDOWS\system32
C:\Program Files\QGIS 3.40.8\bin\python312.zip
C:\PROGRA~1\QGIS34~1.8\apps\Python312\DLLs
C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib
C:\Program Files\QGIS 3.40.8\bin
C:\PROGRA~1\QGIS34~1.8\apps\Python312
C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS34~1.8\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/pmagdon/AppData/Roaming/QGIS/QGIS3\profiles\test_hawk/python
C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins
C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins\qgis_stac\lib
C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins\qfieldsync\libqfieldsync_62853968a3cc98953ff7f41f8770a7f9d1b6a80e.whl
C:\Users\pmagdon\AppData\Roaming\QGIS\QGIS3\profiles\test_hawk\python\plugins
